version: '3'
services:
  app:
    image: dimitarrradev/student-registry-app:${LATEST_BUILD}
    ports:
      - "3030:3030" # Map port 3030 on the host to port 3030 in the container
    environment:
      - NODE_ENV=production
